// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    checkbox: string;
    checkboxWrap: string;
    checked: string;
    item: string;
    itemWrap: string;
    label: string;
    nestedSign: string;
    wrap: string;
}
export const cssExports: CssExports;
export default cssExports;
