// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    errorCaption: string;
    input: string;
    inputError: string;
    inputWrap: string;
    wrap: string;
}
export const cssExports: CssExports;
export default cssExports;
