// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    blue: string;
    button: string;
    fileButton: string;
    'ghost-dark': string;
    'ghost-light': string;
}
export const cssExports: CssExports;
export default cssExports;
