// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    button: string;
    fileButton: string;
    'ghost-dark': string;
    'ghost-light': string;
    primary: string;
}
export const cssExports: CssExports;
export default cssExports;
