// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    active: string;
    button: string;
    fileButton: string;
    outline: string;
    primary: string;
}
export const cssExports: CssExports;
export default cssExports;
