// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    buttonsWrap: string;
    reset: string;
    wrap: string;
}
export const cssExports: CssExports;
export default cssExports;
