// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    info: string;
    infoIcon: string;
    text: string;
    wrap: string;
}
export const cssExports: CssExports;
export default cssExports;
