// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    buttonsSection: string;
    caption: string;
    head: string;
    logo: string;
    wrap: string;
}
export const cssExports: CssExports;
export default cssExports;
