// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    background: string;
    button: string;
    buttonWrap: string;
    eyes: string;
    head: string;
    jason: string;
    logo: string;
    nes1989: string;
}
export const cssExports: CssExports;
export default cssExports;
