// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    eyes: string;
    head: string;
    logo: string;
}
export const cssExports: CssExports;
export default cssExports;
