// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    actionButtons: string;
    button: string;
    buttonsWrap: string;
    icon: string;
    manipulationButtons: string;
    wrap: string;
}
export const cssExports: CssExports;
export default cssExports;
