// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    fileSection: string;
    fileSection_info: string;
    fileSection_info_icon: string;
    fileSection_info_text: string;
    wrap: string;
}
export const cssExports: CssExports;
export default cssExports;
