// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    hidden: string;
    visible: string;
    wrap: string;
}
export const cssExports: CssExports;
export default cssExports;
